#include <iostream>
#include <fstream>
#include <cstring>
#include <string>
#include "TH1F.h"
using namespace std;
//#define nfile 4
#define nGJet 4

void xMerge_GJet(){
  TString rootname[10] = {
			  
			  "/home/judy/ntuhep/GMET/output_file/summer16/mc/summer16_CRABdata_sigMC_HT-100To200_13TeV-madgraphMLM-pythia8_v3-v2_16_05_2021/210609_112107/output_ggtree.root",
			  "/home/judy/ntuhep/GMET/output_file/summer16/mc/summer16_CRABdata_sigMC_HT-200To400_13TeV-madgraphMLM-pythia8_v3-v2_16_05_2021/210609_114738/output_ggtree.root",
			  "/home/judy/ntuhep/GMET/output_file/summer16/mc/summer16_CRABdata_sigMC_HT-400To600_13TeV-madgraphMLM-pythia8_v3-v2_16_05_2021/210609_121431/output_ggtree.root",
			  "/home/judy/ntuhep/GMET/output_file/summer16/mc/summer16_CRABdata_sigMC_HT-600ToInf_13TeV-madgraphMLM-pythia8_v3-v2_16_05_2021/210607_104220/output_ggtree.root"
			 
  };//8 gjet

  //Float_t mcXsec[10] = {9319, 9155, 2323, 2314, 278.5, 271.8, 93.85, 94.7};
  Float_t mcXsec[10] = {9155, 2314, 271.8, 94.7};
  
  Float_t Xsec = 2323;
  Float_t lumi16 = 36.33;
  
  TH1F *H_Events;
  TH1F *H_npho;
  TH1F *H_nmcpho;
  TH1F *H_nmatchpho;
  TH1F *H_dr_pho;
  TH1F *H_dpt_pho;
  TH1F *H_njet_Nm1;
  TH1F *H_njet_cut;
  TH1F *H_phoEB_pt;
  TH1F *H_phoEB_pt_200;
  TH1F *H_phoEB_pt_M;
  TH1F *H_phoEB_pt_chworst;
  TH1F *H_phoEB_pt_r9;
  TH1F *H_phoEB_pt_phoptoverMET;
  TH1F *H_phoEB_pt_MET;
  TH1F *H_phoEB_pt_dphoMETPhi;
  TH1F *H_phoEB_pt_jetveto;
  TH1F *H_phoEB_pt_djetMETPhi;
  TH1F *H_phoEB_pt_HLT;
  TH1F *H_phoEB_ptoverMET;
  TH1F *H_phoEB_eta;
  TH1F *H_phoEB_eta_M;
  TH1F *H_jetpt_Nm1;
  TH1F *H_jetpt_cut;
  TH1F *H_phoEB_ptoverjetpt;
  TH1F *H_MET_Nm1;
  TH1F *H_MET_cut;
  TH1F *H_dphoMETPhi_Nm1;
  TH1F *H_dphoMETPhi_cut;
  TH1F *H_phoEB_ptMid;
  TH1F *H_phoEB_ptcut;
  TH1F *H_djetMETPhi_Nm1;
  TH1F *H_djetMETPhi_cut;
  TH1F *H_nvtx_Nm1;
  TH1F *H_nvtx_cut;
  TH2F *H2_rho_phoEB_pt_M;
  TH2F *H2_rho_phoEB_pt_chworst;
  TH2F *H2_rho_phoEB_pt_chworst_newEA;
  
  TH1F *HA_Events;
  TH1F *HA_npho;
  TH1F *HA_nmcpho;
  TH1F *HA_nmatchpho;
  TH1F *HA_dr_pho;
  TH1F *HA_dpt_pho;
  TH1F *HA_njet_Nm1;
  TH1F *HA_njet_cut;
  TH1F *HA_phoEB_pt;
  TH1F *HA_phoEB_pt_200;
  TH1F *HA_phoEB_pt_M;
  TH1F *HA_phoEB_pt_chworst;
  TH1F *HA_phoEB_pt_r9;
  TH1F *HA_phoEB_pt_phoptoverMET;
  TH1F *HA_phoEB_pt_MET;
  TH1F *HA_phoEB_pt_dphoMETPhi;
  TH1F *HA_phoEB_pt_jetveto;
  TH1F *HA_phoEB_pt_djetMETPhi;
  TH1F *HA_phoEB_pt_HLT;
  TH1F *HA_phoEB_ptoverMET;
  TH1F *HA_phoEB_eta;
  TH1F *HA_phoEB_eta_M;
  TH1F *HA_jetpt_Nm1;
  TH1F *HA_jetpt_cut;
  TH1F *HA_phoEB_ptoverjetpt;
  TH1F *HA_MET_Nm1;
  TH1F *HA_MET_cut;
  TH1F *HA_dphoMETPhi_Nm1;
  TH1F *HA_dphoMETPhi_cut;
  TH1F *HA_phoEB_ptMid;
  TH1F *HA_phoEB_ptcut;
  TH1F *HA_djetMETPhi_Nm1;
  TH1F *HA_djetMETPhi_cut;
  TH1F *HA_nvtx_Nm1;
  TH1F *HA_nvtx_cut;
  TH2F *HA2_rho_phoEB_pt_M;
  TH2F *HA2_rho_phoEB_pt_chworst;
  TH2F *HA2_rho_phoEB_pt_chworst_newEA;
  
  TFile *fopen, *fout;
  TCanvas *c1 = new TCanvas("c1");
  TTree *t;
  Int_t entries;
  Float_t outentries = 0.;
  Float_t scale = 0.;

  for(Int_t i=0; i<nGJet;i++){
    fopen = new TFile(rootname[i]);
    HA_Events = (TH1F*)fopen->Get("hEvents");
    entries = HA_Events->GetBinContent(1);
    outentries = mcXsec[i]*1000*lumi16;
    scale = Xsec/mcXsec[i];
    //scale = outentries/entries;
    if(i==0){
      HA_Events = (TH1F*)fopen->Get("hEvents")->Clone();
      
      HA_npho = (TH1F*)fopen->Get("h_npho")->Clone();
      HA_nmcpho = (TH1F*)fopen->Get("h_nmcpho")->Clone();
      HA_nmatchpho = (TH1F*)fopen->Get("h_nmatchpho")->Clone();
      HA_dr_pho = (TH1F*)fopen->Get("h_dr_pho")->Clone();
      HA_dpt_pho = (TH1F*)fopen->Get("h_dpt_pho")->Clone();
      HA_phoEB_pt = (TH1F*)fopen->Get("h_phoEB_pt")->Clone();
      HA_njet_Nm1 = (TH1F*)fopen->Get("h_njet_Nm1")->Clone();
      HA_njet_cut = (TH1F*)fopen->Get("h_njet_cut")->Clone();
      HA_phoEB_pt = (TH1F*)fopen->Get("h_phoEB_pt")->Clone();
      HA_phoEB_pt_200 = (TH1F*)fopen->Get("h_phoEB_pt_200")->Clone();
      HA_phoEB_pt_M = (TH1F*)fopen->Get("h_phoEB_pt_M")->Clone();
      HA_phoEB_pt_chworst = (TH1F*)fopen->Get("h_phoEB_pt_chworst")->Clone();
      HA_phoEB_pt_r9 = (TH1F*)fopen->Get("h_phoEB_pt_r9")->Clone();
      HA_phoEB_pt_phoptoverMET = (TH1F*)fopen->Get("h_phoEB_pt_phoptoverMET")->Clone();
      HA_phoEB_pt_MET = (TH1F*)fopen->Get("h_phoEB_pt_MET")->Clone();
      HA_phoEB_pt_dphoMETPhi = (TH1F*)fopen->Get("h_phoEB_pt_dphoMETPhi")->Clone();
      HA_phoEB_pt_jetveto = (TH1F*)fopen->Get("h_phoEB_pt_jetveto")->Clone();
      HA_phoEB_pt_djetMETPhi = (TH1F*)fopen->Get("h_phoEB_pt_djetMETPhi")->Clone();
      HA_phoEB_pt_HLT = (TH1F*)fopen->Get("h_phoEB_pt_HLT")->Clone();
      HA_phoEB_ptoverMET = (TH1F*)fopen->Get("h_phoEB_ptoverMET")->Clone();
      HA_phoEB_eta = (TH1F*)fopen->Get("h_phoEB_eta")->Clone();
      HA_phoEB_eta_M = (TH1F*)fopen->Get("h_phoEB_eta_M")->Clone();
      HA_jetpt_Nm1 = (TH1F*)fopen->Get("h_jetpt_Nm1")->Clone();
      HA_jetpt_cut = (TH1F*)fopen->Get("h_jetpt_cut")->Clone();
      HA_phoEB_ptoverjetpt = (TH1F*)fopen->Get("h_phoEB_ptoverjetpt")->Clone();
      HA_MET_Nm1 = (TH1F*)fopen->Get("h_MET_Nm1")->Clone();
      HA_MET_cut = (TH1F*)fopen->Get("h_MET_cut")->Clone();
      HA_dphoMETPhi_Nm1 = (TH1F*)fopen->Get("h_dphoMETPhi_Nm1")->Clone();
      HA_dphoMETPhi_cut = (TH1F*)fopen->Get("h_dphoMETPhi_cut")->Clone();
      HA_phoEB_ptMid = (TH1F*)fopen->Get("h_phoEB_ptMid")->Clone();
      HA_phoEB_ptcut = (TH1F*)fopen->Get("h_phoEB_ptcut")->Clone();
      HA_djetMETPhi_Nm1 = (TH1F*)fopen->Get("h_djetMETPhi_Nm1")->Clone();
      HA_djetMETPhi_cut = (TH1F*)fopen->Get("h_djetMETPhi_cut")->Clone();
      HA_nvtx_Nm1 = (TH1F*)fopen->Get("h_nvtx_Nm1")->Clone();
      HA_nvtx_cut = (TH1F*)fopen->Get("h_nvtx_cut")->Clone();
      HA2_rho_phoEB_pt_M = (TH2F*)fopen->Get("h2_rho_phoEB_pt_M")->Clone();
      HA2_rho_phoEB_pt_chworst = (TH2F*)fopen->Get("h2_rho_phoEB_pt_chworst")->Clone();
      HA2_rho_phoEB_pt_chworst_newEA = (TH2F*)fopen->Get("h2_rho_phoEB_pt_chworst_newEA")->Clone();

      HA_Events->Scale(scale);
      HA_npho->Scale(scale);
      HA_nmcpho->Scale(scale);
      HA_nmatchpho->Scale(scale);
      HA_dr_pho->Scale(scale);
      HA_dpt_pho->Scale(scale);
      HA_njet_Nm1->Scale(scale);
      HA_njet_cut->Scale(scale);
      HA_phoEB_pt->Scale(scale);
      HA_phoEB_pt_200->Scale(scale);
      HA_phoEB_pt_M->Scale(scale);
      HA_phoEB_pt_chworst->Scale(scale);
      HA_phoEB_pt_r9->Scale(scale);
      HA_phoEB_pt_phoptoverMET->Scale(scale);
      HA_phoEB_pt_MET->Scale(scale);
      HA_phoEB_pt_dphoMETPhi->Scale(scale);
      HA_phoEB_pt_jetveto->Scale(scale);
      HA_phoEB_pt_djetMETPhi->Scale(scale);
      HA_phoEB_pt_HLT->Scale(scale);
      HA_phoEB_ptoverMET->Scale(scale);
      HA_phoEB_eta->Scale(scale);
      HA_phoEB_eta_M->Scale(scale);
      HA_jetpt_Nm1->Scale(scale);
      HA_jetpt_cut->Scale(scale);
      HA_phoEB_ptoverjetpt->Scale(scale);
      HA_MET_Nm1->Scale(scale);
      HA_MET_cut->Scale(scale);
      HA_dphoMETPhi_Nm1->Scale(scale);
      HA_dphoMETPhi_cut->Scale(scale);
      HA_phoEB_ptMid->Scale(scale);
      HA_phoEB_ptcut->Scale(scale);
      HA_djetMETPhi_Nm1->Scale(scale);
      HA_djetMETPhi_cut->Scale(scale);
      HA_nvtx_Nm1->Scale(scale);
      HA_nvtx_cut->Scale(scale);
      HA2_rho_phoEB_pt_M->Scale(scale);
      HA2_rho_phoEB_pt_chworst->Scale(scale);
      HA2_rho_phoEB_pt_chworst_newEA->Scale(scale);

      HA_Events->SetDirectory(0);
      HA_npho->SetDirectory(0);
      HA_nmcpho->SetDirectory(0);
      HA_nmatchpho->SetDirectory(0);
      HA_dr_pho->SetDirectory(0);
      HA_dpt_pho->SetDirectory(0);
      HA_phoEB_pt->SetDirectory(0);
      HA_njet_Nm1->SetDirectory(0);
      HA_njet_cut->SetDirectory(0);
      HA_phoEB_pt->SetDirectory(0);
      HA_phoEB_pt_200->SetDirectory(0);
      HA_phoEB_pt_M->SetDirectory(0);
      HA_phoEB_pt_chworst->SetDirectory(0);
      HA_phoEB_pt_r9->SetDirectory(0);
      HA_phoEB_pt_phoptoverMET->SetDirectory(0);
      HA_phoEB_pt_MET->SetDirectory(0);
      HA_phoEB_pt_dphoMETPhi->SetDirectory(0);
      HA_phoEB_pt_jetveto->SetDirectory(0);
      HA_phoEB_pt_djetMETPhi->SetDirectory(0);
      HA_phoEB_pt_HLT->SetDirectory(0);
      HA_phoEB_ptoverMET->SetDirectory(0);
      HA_phoEB_eta->SetDirectory(0);
      HA_phoEB_eta_M->SetDirectory(0);
      HA_jetpt_Nm1->SetDirectory(0);
      HA_jetpt_cut->SetDirectory(0);
      HA_phoEB_ptoverjetpt->SetDirectory(0);
      HA_MET_Nm1->SetDirectory(0);
      HA_MET_cut->SetDirectory(0);
      HA_dphoMETPhi_Nm1->SetDirectory(0);
      HA_dphoMETPhi_cut->SetDirectory(0);
      HA_phoEB_ptMid->SetDirectory(0);
      HA_phoEB_ptcut->SetDirectory(0);
      HA_djetMETPhi_Nm1->SetDirectory(0);
      HA_djetMETPhi_cut->SetDirectory(0);
      HA_nvtx_Nm1->SetDirectory(0);
      HA_nvtx_cut->SetDirectory(0);
      HA2_rho_phoEB_pt_M->SetDirectory(0);
      HA2_rho_phoEB_pt_chworst->SetDirectory(0);
      HA2_rho_phoEB_pt_chworst_newEA->SetDirectory(0);
    }
    
    H_Events = (TH1F*)fopen->Get("hEvents");
    H_npho = (TH1F*)fopen->Get("h_npho");
    H_nmcpho = (TH1F*)fopen->Get("h_nmcpho");
    H_nmatchpho = (TH1F*)fopen->Get("h_nmatchpho");
    H_dr_pho = (TH1F*)fopen->Get("h_dr_pho");
    H_dpt_pho = (TH1F*)fopen->Get("h_dpt_pho");
    H_phoEB_pt = (TH1F*)fopen->Get("h_phoEB_pt");
    H_njet_Nm1 = (TH1F*)fopen->Get("h_njet_Nm1");
    H_njet_cut = (TH1F*)fopen->Get("h_njet_cut");
    H_phoEB_pt = (TH1F*)fopen->Get("h_phoEB_pt");
    H_phoEB_pt_200 = (TH1F*)fopen->Get("h_phoEB_pt_200");
    H_phoEB_pt_M = (TH1F*)fopen->Get("h_phoEB_pt_M");
    H_phoEB_pt_chworst = (TH1F*)fopen->Get("h_phoEB_pt_chworst");
    H_phoEB_pt_r9 = (TH1F*)fopen->Get("h_phoEB_pt_r9");
    H_phoEB_pt_phoptoverMET = (TH1F*)fopen->Get("h_phoEB_pt_phoptoverMET");
    H_phoEB_pt_MET = (TH1F*)fopen->Get("h_phoEB_pt_MET");
    H_phoEB_pt_dphoMETPhi = (TH1F*)fopen->Get("h_phoEB_pt_dphoMETPhi");
    H_phoEB_pt_jetveto = (TH1F*)fopen->Get("h_phoEB_pt_jetveto");
    H_phoEB_pt_djetMETPhi = (TH1F*)fopen->Get("h_phoEB_pt_djetMETPhi");
    H_phoEB_pt_HLT = (TH1F*)fopen->Get("h_phoEB_pt_HLT");
    H_phoEB_ptoverMET = (TH1F*)fopen->Get("h_phoEB_ptoverMET");
    H_phoEB_eta = (TH1F*)fopen->Get("h_phoEB_eta");
    H_phoEB_eta_M = (TH1F*)fopen->Get("h_phoEB_eta_M");
    H_jetpt_Nm1 = (TH1F*)fopen->Get("h_jetpt_Nm1");
    H_jetpt_cut = (TH1F*)fopen->Get("h_jetpt_cut");
    H_phoEB_ptoverjetpt = (TH1F*)fopen->Get("h_phoEB_ptoverjetpt");
    H_MET_Nm1 = (TH1F*)fopen->Get("h_MET_Nm1");
    H_MET_cut = (TH1F*)fopen->Get("h_MET_cut");
    H_dphoMETPhi_Nm1 = (TH1F*)fopen->Get("h_dphoMETPhi_Nm1");
    H_dphoMETPhi_cut = (TH1F*)fopen->Get("h_dphoMETPhi_cut");
    H_phoEB_ptMid = (TH1F*)fopen->Get("h_phoEB_ptMid");
    H_phoEB_ptcut = (TH1F*)fopen->Get("h_phoEB_ptcut");
    H_djetMETPhi_Nm1 = (TH1F*)fopen->Get("h_djetMETPhi_Nm1");
    H_djetMETPhi_cut = (TH1F*)fopen->Get("h_djetMETPhi_cut");
    H_nvtx_Nm1 = (TH1F*)fopen->Get("h_nvtx_Nm1");
    H_nvtx_cut = (TH1F*)fopen->Get("h_nvtx_cut");
    H2_rho_phoEB_pt_M = (TH2F*)fopen->Get("h2_rho_phoEB_pt_M");
    H2_rho_phoEB_pt_chworst = (TH2F*)fopen->Get("h2_rho_phoEB_pt_chworst");
    H2_rho_phoEB_pt_chworst_newEA = (TH2F*)fopen->Get("h2_rho_phoEB_pt_chworst_newEA");

    H_Events->Scale(scale);
    H_npho->Scale(scale);
    H_nmcpho->Scale(scale);
    H_nmatchpho->Scale(scale);
    H_dr_pho->Scale(scale);
    H_dpt_pho->Scale(scale);
    H_phoEB_pt->Scale(scale);
    H_njet_Nm1->Scale(scale);
    H_njet_cut->Scale(scale);
    H_phoEB_pt->Scale(scale);
    H_phoEB_pt_200->Scale(scale);
    H_phoEB_pt_M->Scale(scale);
    H_phoEB_pt_chworst->Scale(scale);
    H_phoEB_pt_r9->Scale(scale);
    H_phoEB_pt_phoptoverMET->Scale(scale);
    H_phoEB_pt_MET->Scale(scale);
    H_phoEB_pt_dphoMETPhi->Scale(scale);
    H_phoEB_pt_jetveto->Scale(scale);
    H_phoEB_pt_djetMETPhi->Scale(scale);
    H_phoEB_pt_HLT->Scale(scale);
    H_phoEB_ptoverMET->Scale(scale);
    H_phoEB_eta->Scale(scale);
    H_phoEB_eta_M->Scale(scale);
    H_jetpt_Nm1->Scale(scale);
    H_jetpt_cut->Scale(scale);
    H_phoEB_ptoverjetpt->Scale(scale);
    H_MET_Nm1->Scale(scale);
    H_MET_cut->Scale(scale);
    H_dphoMETPhi_Nm1->Scale(scale);
    H_dphoMETPhi_cut->Scale(scale);
    H_dphoMETPhi_HLT->Scale(scale);
    H_phoEB_ptMid->Scale(scale);
    H_phoEB_ptcut->Scale(scale);
    H_djetMETPhi_Nm1->Scale(scale);
    H_djetMETPhi_cut->Scale(scale);
    H2_nvtx_njet_Nm1->Scale(scale);
    H2_nvtx_njet_cut->Scale(scale);
    H_nvtx_Nm1->Scale(scale);
    H_nvtx_cut->Scale(scale);
    H2_rho_phoEB_pt_M->Scale(scale);
    H2_rho_phoEB_pt_chworst->Scale(scale);
    H2_rho_phoEB_pt_chworst_newEA->Scale(scale);

    HA_Events->Add(H_Events);
    HA_npho->Add(H_npho);
    HA_nmcpho->Add(H_nmcpho);
    HA_nmatchpho->Add(H_nmatchpho);
    HA_dr_pho->Add(H_dr_pho);
    HA_dpt_pho->Add(H_dpt_pho);
    HA_njet_Nm1->Add(H_njet_Nm1);
    HA_njet_cut->Add(H_njet_cut);
    HA_phoEB_pt->Add(H_phoEB_pt);
    HA_phoEB_pt_200->Add(H_phoEB_pt_200);
    HA_phoEB_pt_M->Add(H_phoEB_pt_M);
    HA_phoEB_pt_chworst->Add(H_phoEB_pt_chworst);
    HA_phoEB_pt_r9->Add(H_phoEB_pt_r9);
    HA_phoEB_pt_phoptoverMET->Add(H_phoEB_pt_phoptoverMET);
    HA_phoEB_pt_MET->Add(H_phoEB_pt_MET);
    HA_phoEB_pt_dphoMETPhi->Add(H_phoEB_pt_dphoMETPhi);
    HA_phoEB_pt_jetveto->Add(H_phoEB_pt_jetveto);
    HA_phoEB_pt_djetMETPhi->Add(H_phoEB_pt_djetMETPhi);
    HA_phoEB_pt_HLT->Add(H_phoEB_pt_HLT);
    HA_phoEB_ptoverMET->Add(H_phoEB_ptoverMET);
    HA_phoEB_eta->Add(H_phoEB_eta);
    HA_phoEB_eta_M->Add(H_phoEB_eta_M);
    HA_jetpt_Nm1->Add(H_jetpt_Nm1);
    HA_jetpt_cut->Add(H_jetpt_cut);
    HA_phoEB_ptoverjetpt->Add(H_phoEB_ptoverjetpt);
    HA_MET_Nm1->Add(H_MET_Nm1);
    HA_MET_cut->Add(H_MET_cut);
    HA_dphoMETPhi_Nm1->Add(H_dphoMETPhi_Nm1);
    HA_dphoMETPhi_cut->Add(H_dphoMETPhi_cut);
    HA_phoEB_ptMid->Add(H_phoEB_ptMid);
    HA_phoEB_ptcut->Add(H_phoEB_ptcut);
    HA_djetMETPhi_Nm1->Add(H_djetMETPhi_Nm1);
    HA_djetMETPhi_cut->Add(H_djetMETPhi_cut);
    HA_nvtx_Nm1->Add(H_nvtx_Nm1);
    HA_nvtx_cut->Add(H_nvtx_cut);
    HA2_rho_phoEB_pt_M->Add(H2_rho_phoEB_pt_M);
    HA2_rho_phoEB_pt_chworst->Add(H2_rho_phoEB_pt_chworst);
    HA2_rho_phoEB_pt_chworst_newEA->Add(H2_rho_phoEB_pt_chworst_newEA);
  }

  fout = new TFile("output_merge.root", "RECREATE");
  
  HA_Events->Write();
  HA_npho->Write();
  HA_nmcpho->Write();
  HA_nmatchpho->Write();
  HA_dr_pho->Write();
  HA_dpt_pho->Write();
  HA_njet_Nm1->Write();
  HA_njet_cut->Write();
  HA_phoEB_pt->Write();
  HA_phoEB_pt_200->Write();
  HA_phoEB_pt_M->Write();
  HA_phoEB_pt_chworst->Write();
  HA_phoEB_pt_r9->Write();
  HA_phoEB_pt_phoptoverMET->Write();
  HA_phoEB_pt_MET->Write();
  HA_phoEB_pt_dphoMETPhi->Write();
  HA_phoEB_pt_jetveto->Write();
  HA_phoEB_pt_djetMETPhi->Write();
  HA_phoEB_pt_HLT->Write();
  HA_phoEB_ptoverMET->Write();
  HA_phoEB_eta->Write();
  HA_phoEB_eta_M->Write();
  HA_jetpt_Nm1->Write();
  HA_jetpt_cut->Write();
  HA_phoEB_ptoverjetpt->Write();
  HA_MET_Nm1->Write();
  HA_MET_cut->Write();
  HA_dphoMETPhi_Nm1->Write();
  HA_dphoMETPhi_cut->Write();
  HA_phoEB_ptMid->Write();
  HA_phoEB_ptcut->Write();
  HA_djetMETPhi_Nm1->Write();
  HA_djetMETPhi_cut->Write();
  HA_nvtx_Nm1->Write();
  HA_nvtx_cut->Write();
  HA2_rho_phoEB_pt_M->Write();
  HA2_rho_phoEB_pt_chworst->Write();
  HA2_rho_phoEB_pt_chworst_newEA->Write();
  
}
